Repository hatchways/team-brioche, pull requests merged in 2021-10, with the labels that each got.

#73 HotFix -Made slight improvements for cleaner routes
  client/src/App.tsx
  client/src/Layout/DashboardLayout.tsx
  client/src/components/ProfileListings/ProfileListings/useStyles.ts
  client/src/components/ProtectedRoute/ProtectedRoute.tsx
Labels: enhancement

#71 Implementation of the landing page
  client/src/App.tsx
  client/src/Layout/DashboardLayout.tsx
  client/src/components/ProfileListings/ProfileListings/useStyles.ts
  client/src/components/ProtectedRoute/ProtectedRoute.tsx
Labels: Frontend

#74 resolve name conflicts
  client/package-lock.json
  client/src/App.tsx
  client/src/context/useAuthContext.tsx
  client/src/interface/Profile.ts
  client/src/mocks/mockProfile.ts
  client/src/pages/EditProfile/EditProfile.tsx
  client/src/pages/EditProfile/EditProfileForm/EditProfileForm.tsx
  client/src/pages/ProfileDetails/ProfileDetails.tsx
  client/src/pages/ProfileDetails/useStyles.ts
Labels: bug

#77 HotFix - cleanedup-routes
  client/src/App.tsx
  client/src/Layout/DashboardLayout.tsx
  client/src/components/ProtectedRoute/ProtectedRoute.tsx
Labels: duplicate, Frontend
