Repository hatchways/team-brioche, pull requests merged in 2021-09, with the labels that each got.

#58 Implementation of the login/signup page
  client/src/App.tsx
  client/src/components/Redirect/Redirect.tsx
  client/src/components/Redirect/useStyles.ts
  client/src/components/UserAccountWrapper/UserAccountWrapper.tsx
  client/src/components/UserAccountWrapper/useStyles.ts
  client/src/interface/UserAccount.ts
  client/src/pages/Accounts/AuthForm/LoginForm/LoginForm.test.tsx
  client/src/pages/Accounts/AuthForm/LoginForm/LoginForm.tsx
  client/src/pages/Accounts/AuthForm/SignupForm/SignUpForm.test.tsx
  client/src/pages/Accounts/AuthForm/SignupForm/SignUpForm.tsx
  client/src/pages/Accounts/AuthForm/useStyles.ts
  client/src/pages/Accounts/Login/Login.test.tsx
  client/src/pages/Accounts/Login/Login.tsx
  client/src/pages/Accounts/Signup/SignUp.test.tsx
  client/src/pages/Accounts/Signup/SignUp.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Login/LoginForm/useStyles.ts
  client/src/pages/Login/useStyles.ts
  client/src/pages/SignUp/SignUp.tsx
  client/src/pages/SignUp/SignUpForm/useStyles.ts
  client/src/pages/SignUp/useStyles.ts
Labels: Frontend

#59 Implementation of Demo User
  client/src/components/DemoUser/DemoUser.tsx
  client/src/components/DemoUser/useStyles.ts
  client/src/components/ProfilePhoto/ProfileAvatar/ProfileAvatar.tsx
  client/src/components/ProfilePhoto/ProfileAvatar/useStyles.ts
  client/src/components/ProfilePhoto/ProfilePhoto.tsx
  client/src/components/UserAccountWrapper/UserAccountWrapper.tsx
  client/src/components/UserAccountWrapper/useStyles.ts
  client/src/pages/Accounts/Login/Login.tsx
  client/src/pages/Accounts/Signup/SignUp.tsx
  server/middleware/error.js
  server/seed.js
Labels: Frontend

#61 Update to the Profile-model and Profile-interface
  client/src/interface/Profile.ts
  server/models/Profile.js
Labels: bug

#55 Feature profile integration
  .gitignore
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/context/useAuthContext.tsx
  client/src/helpers/APICalls/profile.ts
  client/src/interface/Profile.ts
  client/src/mocks/mockProfile.ts
  client/src/mocks/mockUseAuthProvider.tsx
  client/src/pages/EditProfile/EditProfile.tsx
  client/src/pages/EditProfile/EditProfileForm/DateSelector.tsx
  client/src/pages/EditProfile/EditProfileForm/EditProfileForm.tsx
  client/src/pages/EditProfile/EditProfileForm/Label.tsx
  client/src/pages/EditProfile/EditProfileForm/useInputState.tsx
  client/src/pages/EditProfile/EditProfileForm/useStyles.ts
  client/src/pages/EditProfile/useStyles.ts
  server/controllers/profile.js
  server/models/Profile.js
  server/package-lock.json
  server/routes/profile.js
  server/routes/user.js
Labels: Week 1
